Add static HTML output option from slack2html
hfaran/slack-export-viewer pull request #177
Opened 2023-11-22 13:53 UTC by merobi-hub

The separate project slack2html serves a common use case -- publishing an archive on a host -- but, being a separate project, is not very convenient.

This borrows that project's dependencies, CustomFreezer class, and instantiation to add an option to output static HTML to any specified directory. The class is in a new script in slackviewer. The only changes to the implementation are the addition of a new command-line argument and a default output directory.

![Screenshot 2023-11-21 at 22 35 53](https://github.com/hfaran/slack-export-viewer/assets/68482867/903e9c12-e81f-4b56-a592-db623f80decf)

2023-11-22 14:28 UTC, merobi-hub commented
I used it to generate a [simple archive site](https://openlineage.github.io/slack-archives/)

2023-12-16 10:01 UTC, hfaran requested changes

2023-12-16 10:01 UTC, hfaran commented on slackviewer/main.py
> +            webbrowser.open("file:///{}/index.html"
Does this work across all platforms?

2023-12-16 10:01 UTC, hfaran commented on slackviewer/freezer.py
> +from flask_frozen import Freezer
Can you add this package to requirements.txt? The current tests are failing because this is not added as a requirement.

2023-12-16 13:36 UTC, merobi-hub commented on slackviewer/freezer.py
> +from flask_frozen import Freezer
Done, thanks

2023-12-16 13:41 UTC, merobi-hub commented on slackviewer/main.py
> +            webbrowser.open("file:///{}/index.html"
This code is unchanged from slack2html. Unfortunately, I've only been able to test this on MacOS, but I assume it will work on all the platforms supported by slack2html.

2023-12-16 19:58 UTC, hfaran approved these changes

2023-12-16 19:58 UTC, merged